version: "1.0"

# Who owns/runs this runtime
dominion:
  root_env_var: FORGE_DOMINION_ROOT     # one-variable-to-rule-them-all
  service_ttl_minutes: 180              # lifetime for minted tokens
  allow_unsigned: false                 # block runs if sig invalid

# Runtime configuration for Forge integration
runtime:
  name: sr-aibridge
  forge:
    mode: dominion
    handshake: forge://resolve
    targets:
      - name: sovereign-ledger
        type: log
        scope: deploy
        verify: true
  # Federation heartbeat configuration
  federation:
    heartbeat:
      enabled: true
      interval: 60
      endpoint: forge://federation/heartbeat
      ledger_forward: true
      ttl: 300
    consensus:
      enabled: true
      interval: 180
      election_method: highest_epoch
      ledger_forward: true

# Forge configuration schema
forge:
  dominion: sovereign.bridge
  resolver: forge://resolve
  schema:
    - target: ledger
      purpose: runtime logging
      return:
        - ledger_url
        - ledger_signature
        - ledger_identity
    - target: bridge
      purpose: deployment bridge sync
      return:
        - bridge_url
        - bridge_signature
        - bridge_identity

# Where to run (Phase-1 = local/host Docker)
provider:
  kind: docker
  network: brh_net
  autostart: true

# Services to launch (examples)
services:
  api:
    context: ./bridge_backend
    dockerfile: Dockerfile    # optional; builds if context present, else pulls image
    image: ghcr.io/kswhitlock9493-jpg/sr-aibridge-backend:latest
    replicas: 1
    ports:
      - "8000:8000"
    env:
      - "ENVIRONMENT=production"
      - "LOG_LEVEL=INFO"
    health:
      http: "http://localhost:8000/health/live"
      interval: 10s
      timeout: 2s
      retries: 12
    volumes: []               # e.g. - "./data:/app/data"

  ws:
    image: ghcr.io/kswhitlock9493-jpg/ws-sidecar:latest
    replicas: 1
    depends_on: [api]
    env:
      - "BACKEND_URL=http://api:8000"
    health:
      tcp: "localhost:9001"
      interval: 10s
      timeout: 2s
      retries: 12
