"""
EnvScribe Emitters
Generates copy-ready environment blocks and Truth-certified documentation
"""

import logging
from pathlib import Path
from typing import Dict, List, Any
from .models import EnvScribeReport, EnvVariable, VerificationStatus

logger = logging.getLogger(__name__)


class EnvScribeEmitter:
    """
    Generates output artifacts from EnvScribe reports:
    - Copy-ready environment blocks for Render, Netlify, GitHub
    - ENV_OVERVIEW.md documentation
    - Platform-specific configuration files
    """
    
    def __init__(self):
        self.repo_root = Path(__file__).resolve().parents[3]
        self.docs_path = self.repo_root / "docs"
        self.diagnostics_path = self.repo_root / "bridge_backend" / "diagnostics"
        
        # Ensure directories exist
        self.docs_path.mkdir(parents=True, exist_ok=True)
        self.diagnostics_path.mkdir(parents=True, exist_ok=True)
    
    def emit_all(self, report: EnvScribeReport) -> Dict[str, str]:
        """
        Generate all output artifacts
        
        Returns:
            Dictionary of generated file paths
        """
        outputs = {}
        
        # Generate ENV_OVERVIEW.md
        overview_path = self.emit_env_overview(report)
        outputs["overview"] = str(overview_path)
        
        # Generate copy blocks
        copy_blocks = self.generate_copy_blocks(report)
        outputs["copy_blocks"] = copy_blocks
        
        # Generate platform configs
        render_config = self.emit_render_config(report)
        netlify_config = self.emit_netlify_config(report)
        github_config = self.emit_github_config(report)
        
        outputs["render_config"] = str(render_config)
        outputs["netlify_config"] = str(netlify_config)
        outputs["github_config"] = str(github_config)
        
        logger.info(f"[EnvScribe Emitter] Generated {len(outputs)} output files")
        return outputs
    
    def emit_env_overview(self, report: EnvScribeReport) -> Path:
        """Generate ENV_OVERVIEW.md with Truth-certified summary"""
        overview_path = self.docs_path / "ENV_OVERVIEW.md"
        
        content = self._generate_env_overview_content(report)
        
        with open(overview_path, 'w') as f:
            f.write(content)
        
        logger.info(f"[EnvScribe Emitter] Generated {overview_path}")
        return overview_path
    
    def _generate_env_overview_content(self, report: EnvScribeReport) -> str:
        """Generate content for ENV_OVERVIEW.md"""
        lines = [
            "# Environment Overview",
            "",
            f"**Generated by EnvScribe** | {report.summary.timestamp}",
            ""
        ]
        
        if report.certified:
            lines.extend([
                f"✅ **Truth-Certified** | Certificate ID: `{report.certificate_id}`",
                ""
            ])
        
        # Summary section
        lines.extend([
            "## Summary",
            "",
            f"- **Total Variables**: {report.summary.total_keys}",
            f"- **Verified**: {report.summary.verified}",
            f"- **Missing in Render**: {report.summary.missing_in_render}",
            f"- **Missing in Netlify**: {report.summary.missing_in_netlify}",
            f"- **Missing in GitHub**: {report.summary.missing_in_github}",
            f"- **Drifted**: {report.summary.drifted}",
            "",
            "## Variables",
            "",
            "| Variable | Scope | Type | Default | Verified | Description |",
            "|----------|-------|------|---------|----------|-------------|"
        ])
        
        # Sort variables by name
        sorted_vars = sorted(report.variables, key=lambda v: v.name)
        
        for var in sorted_vars:
            scope = "/".join(var.scope)
            default = var.default or "—"
            lines.append(
                f"| {var.name} | {scope} | {var.var_type} | {default} | {var.verified} | {var.description} |"
            )
        
        # Legend
        lines.extend([
            "",
            "### Legend",
            "",
            "- ✅ = verified",
            "- 🟨 = missing value",
            "- 🟥 = absent",
            "- ⚠️ = drifted",
            ""
        ])
        
        # Missing variables section
        if report.missing_in_render or report.missing_in_netlify or report.missing_in_github:
            lines.extend([
                "## Missing Variables",
                ""
            ])
            
            if report.missing_in_render:
                lines.append("### Render")
                lines.append("")
                for var_name in report.missing_in_render:
                    lines.append(f"- `{var_name}`")
                lines.append("")
            
            if report.missing_in_netlify:
                lines.append("### Netlify")
                lines.append("")
                for var_name in report.missing_in_netlify:
                    lines.append(f"- `{var_name}`")
                lines.append("")
            
            if report.missing_in_github:
                lines.append("### GitHub")
                lines.append("")
                for var_name in report.missing_in_github:
                    lines.append(f"- `{var_name}`")
                lines.append("")
        
        # Drifted variables section
        if report.drifted:
            lines.extend([
                "## Drifted Variables",
                "",
                "Variables with different values across platforms:",
                ""
            ])
            
            for var_name, platforms in report.drifted.items():
                lines.append(f"### `{var_name}`")
                lines.append("")
                for platform, value in platforms.items():
                    lines.append(f"- **{platform}**: `{value}`")
                lines.append("")
        
        # Webhooks section
        if report.webhooks:
            lines.extend([
                "## Webhooks",
                "",
                "| Path | Engine | Method | Description |",
                "|------|--------|--------|-------------|"
            ])
            
            for hook in report.webhooks:
                lines.append(
                    f"| {hook.path} | {hook.engine} | {hook.method} | {hook.description} |"
                )
            lines.append("")
        
        return "\n".join(lines)
    
    def generate_copy_blocks(self, report: EnvScribeReport) -> Dict[str, str]:
        """Generate copy-ready environment blocks for each platform"""
        blocks = {
            "render": self._generate_render_block(report),
            "netlify": self._generate_netlify_block(report),
            "github_vars": self._generate_github_vars_block(report),
            "github_secrets": self._generate_github_secrets_block(report)
        }
        
        return blocks
    
    def _generate_render_block(self, report: EnvScribeReport) -> str:
        """Generate Render environment block"""
        lines = ["# Render Environment Variables", ""]
        
        for var in report.variables:
            if "Render" in var.scope or "All" in var.scope:
                if var.var_type == "Secret":
                    lines.append(f"{var.name}=<secret>")
                elif var.default:
                    lines.append(f"{var.name}={var.default}")
                else:
                    lines.append(f"{var.name}=")
        
        return "\n".join(lines)
    
    def _generate_netlify_block(self, report: EnvScribeReport) -> str:
        """Generate Netlify environment block"""
        lines = ["# Netlify Environment Variables", ""]
        
        for var in report.variables:
            if "Netlify" in var.scope or "All" in var.scope:
                if var.var_type == "Secret":
                    lines.append(f"{var.name}=<secret>")
                elif var.default:
                    lines.append(f"{var.name}={var.default}")
                else:
                    lines.append(f"{var.name}=")
        
        return "\n".join(lines)
    
    def _generate_github_vars_block(self, report: EnvScribeReport) -> str:
        """Generate GitHub Variables block (non-secret)"""
        lines = ["# GitHub Variables (Settings → Secrets and variables → Actions → Variables)", ""]
        
        for var in report.variables:
            if "GitHub" in var.scope or "All" in var.scope:
                if var.var_type != "Secret":
                    if var.default:
                        lines.append(f"{var.name}: {var.default}")
                    else:
                        lines.append(f"{var.name}: <value>")
        
        return "\n".join(lines)
    
    def _generate_github_secrets_block(self, report: EnvScribeReport) -> str:
        """Generate GitHub Secrets block"""
        lines = ["# GitHub Secrets (Settings → Secrets and variables → Actions → Secrets)", ""]
        
        for var in report.variables:
            if "GitHub" in var.scope or "All" in var.scope:
                if var.var_type == "Secret":
                    lines.append(f"{var.name}: <paste secret>")
        
        return "\n".join(lines)
    
    def emit_render_config(self, report: EnvScribeReport) -> Path:
        """Emit Render configuration to diagnostics"""
        config_path = self.diagnostics_path / "envscribe_render.env"
        
        content = self._generate_render_block(report)
        
        with open(config_path, 'w') as f:
            f.write(content)
        
        logger.info(f"[EnvScribe Emitter] Generated {config_path}")
        return config_path
    
    def emit_netlify_config(self, report: EnvScribeReport) -> Path:
        """Emit Netlify configuration to diagnostics"""
        config_path = self.diagnostics_path / "envscribe_netlify.env"
        
        content = self._generate_netlify_block(report)
        
        with open(config_path, 'w') as f:
            f.write(content)
        
        logger.info(f"[EnvScribe Emitter] Generated {config_path}")
        return config_path
    
    def emit_github_config(self, report: EnvScribeReport) -> Path:
        """Emit GitHub configuration to diagnostics"""
        config_path = self.diagnostics_path / "envscribe_github.txt"
        
        content = self._generate_github_vars_block(report) + "\n\n"
        content += self._generate_github_secrets_block(report)
        
        with open(config_path, 'w') as f:
            f.write(content)
        
        logger.info(f"[EnvScribe Emitter] Generated {config_path}")
        return config_path
