name: 'Browser Dependency Setup'
description: 'Sets up browser dependencies with firewall bypass support'
inputs:
  skip-chromium:
    description: 'Skip Chromium installation'
    required: false
    default: 'false'
  install-deps:
    description: 'Install Playwright system dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Playwright System Dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        echo "ðŸ“¦ Installing Playwright system dependencies..."
        npx playwright install-deps || echo "âš ï¸ Playwright deps install failed (non-critical)"
    
    - name: Install Chromium Browser
      if: inputs.skip-chromium != 'true'
      shell: bash
      run: |
        echo "ðŸ”§ Skipping Chromium browser download (using system browser to avoid firewall blocks)..."
        echo "âš ï¸ System browser or pre-cached browser will be used instead"
      env:
        PUPPETEER_SKIP_DOWNLOAD: "true"
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
    
    - name: Configure Browser Environment Variables
      shell: bash
      run: |
        echo "ðŸ”§ Configuring browser environment variables..."
        
        # Puppeteer configuration (skip download, use system browser)
        echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" >> $GITHUB_ENV
        echo "PUPPETEER_SKIP_DOWNLOAD=true" >> $GITHUB_ENV
        
        # Playwright configuration (use installed browsers)
        echo "PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=false" >> $GITHUB_ENV
        echo "PLAYWRIGHT_BROWSERS_PATH=0" >> $GITHUB_ENV
        
        # Try to locate Chrome/Chromium
        CHROME_PATH=$(which chromium 2>/dev/null || which chromium-browser 2>/dev/null || which google-chrome 2>/dev/null || echo "")
        if [ -n "$CHROME_PATH" ]; then
          echo "CHROME_BIN=$CHROME_PATH" >> $GITHUB_ENV
          echo "PUPPETEER_EXECUTABLE_PATH=$CHROME_PATH" >> $GITHUB_ENV
          echo "BROWSER_EXECUTABLE_PATH=$CHROME_PATH" >> $GITHUB_ENV
          echo "âœ… Browser configured: $CHROME_PATH"
        else
          echo "âš ï¸ Chrome/Chromium not found in PATH"
        fi
        
        echo "âœ… Browser environment configuration complete"
    
    - name: Verify Browser Installation
      if: inputs.skip-chromium != 'true'
      shell: bash
      run: |
        echo "ðŸ” Verifying browser installation..."
        
        # Check Chromium
        if command -v chromium &> /dev/null || command -v chromium-browser &> /dev/null; then
          CHROMIUM_VERSION=$(chromium --version 2>/dev/null || chromium-browser --version 2>/dev/null || echo "Unknown")
          echo "âœ… Chromium: $CHROMIUM_VERSION"
        else
          echo "âš ï¸ Chromium not found"
        fi
        
        # Check Playwright
        if npx playwright --version &> /dev/null; then
          PLAYWRIGHT_VERSION=$(npx playwright --version 2>/dev/null || echo "Unknown")
          echo "âœ… Playwright: $PLAYWRIGHT_VERSION"
        fi
        
        echo "âœ… Browser setup verification complete"
